packages:
    github.com/Iversy/unified-message-hub/internal/services/hub_service:
        config:
            dir: "{{.InterfaceDir}}/mocks"
            filename: "mocks.go"
            pkgname: "mocks"
            structname: "{{.InterfaceName}}"
        interfaces:
            HubStorage:
    github.com/Iversy/unified-message-hub/internal/api:
        config:
                dir: "{{.InterfaceDir}}/mocks"
                filename: "mocks.go"
                pkgname: "mocks"
                structname: "{{.InterfaceName}}"
        interfaces:
            messageProducer:
            hubService:
            routeProducer:
    github.com/Iversy/unified-message-hub/internal/services/processors/hub_processor:
        config:
                    dir: "{{.InterfaceDir}}/mocks"
                    filename: "mocks.go"
                    pkgname: "mocks"
                    structname: "{{.InterfaceName}}"
        interfaces:
            hubService:
            platformService: