packages:
    github.com/Iversy/unified-message-hub/internal/services/message_service:
        config:
            dir: "{{.InterfaceDir}}/mocks"
            filename: "mocks.go"
            pkgname: "mocks"
            structname: "{{.InterfaceName}}"
        interfaces:
            MessageStorage:
            MessageProducer: