// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Iversy/unified-message-hub/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// newHubService creates a new instance of hubService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newHubService(t interface {
	mock.TestingT
	Cleanup(func())
}) *hubService {
	mock := &hubService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// hubService is an autogenerated mock type for the hubService type
type hubService struct {
	mock.Mock
}

type hubService_Expecter struct {
	mock *mock.Mock
}

func (_m *hubService) EXPECT() *hubService_Expecter {
	return &hubService_Expecter{mock: &_m.Mock}
}

// CreateMessage provides a mock function for the type hubService
func (_mock *hubService) CreateMessage(ctx context.Context, messageInfos []*models.Message) error {
	ret := _mock.Called(ctx, messageInfos)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.Message) error); ok {
		r0 = returnFunc(ctx, messageInfos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// hubService_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type hubService_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - messageInfos []*models.Message
func (_e *hubService_Expecter) CreateMessage(ctx interface{}, messageInfos interface{}) *hubService_CreateMessage_Call {
	return &hubService_CreateMessage_Call{Call: _e.mock.On("CreateMessage", ctx, messageInfos)}
}

func (_c *hubService_CreateMessage_Call) Run(run func(ctx context.Context, messageInfos []*models.Message)) *hubService_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.Message
		if args[1] != nil {
			arg1 = args[1].([]*models.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *hubService_CreateMessage_Call) Return(err error) *hubService_CreateMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *hubService_CreateMessage_Call) RunAndReturn(run func(ctx context.Context, messageInfos []*models.Message) error) *hubService_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveRoutesBySourceChatID provides a mock function for the type hubService
func (_mock *hubService) GetActiveRoutesBySourceChatID(ctx context.Context, chatID int) ([]*models.Route, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveRoutesBySourceChatID")
	}

	var r0 []*models.Route
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Route, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Route); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Route)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// hubService_GetActiveRoutesBySourceChatID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveRoutesBySourceChatID'
type hubService_GetActiveRoutesBySourceChatID_Call struct {
	*mock.Call
}

// GetActiveRoutesBySourceChatID is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int
func (_e *hubService_Expecter) GetActiveRoutesBySourceChatID(ctx interface{}, chatID interface{}) *hubService_GetActiveRoutesBySourceChatID_Call {
	return &hubService_GetActiveRoutesBySourceChatID_Call{Call: _e.mock.On("GetActiveRoutesBySourceChatID", ctx, chatID)}
}

func (_c *hubService_GetActiveRoutesBySourceChatID_Call) Run(run func(ctx context.Context, chatID int)) *hubService_GetActiveRoutesBySourceChatID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *hubService_GetActiveRoutesBySourceChatID_Call) Return(routes []*models.Route, err error) *hubService_GetActiveRoutesBySourceChatID_Call {
	_c.Call.Return(routes, err)
	return _c
}

func (_c *hubService_GetActiveRoutesBySourceChatID_Call) RunAndReturn(run func(ctx context.Context, chatID int) ([]*models.Route, error)) *hubService_GetActiveRoutesBySourceChatID_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertRoute provides a mock function for the type hubService
func (_mock *hubService) UpsertRoute(ctx context.Context, routes []*models.Route) error {
	ret := _mock.Called(ctx, routes)

	if len(ret) == 0 {
		panic("no return value specified for UpsertRoute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.Route) error); ok {
		r0 = returnFunc(ctx, routes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// hubService_UpsertRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertRoute'
type hubService_UpsertRoute_Call struct {
	*mock.Call
}

// UpsertRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - routes []*models.Route
func (_e *hubService_Expecter) UpsertRoute(ctx interface{}, routes interface{}) *hubService_UpsertRoute_Call {
	return &hubService_UpsertRoute_Call{Call: _e.mock.On("UpsertRoute", ctx, routes)}
}

func (_c *hubService_UpsertRoute_Call) Run(run func(ctx context.Context, routes []*models.Route)) *hubService_UpsertRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.Route
		if args[1] != nil {
			arg1 = args[1].([]*models.Route)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *hubService_UpsertRoute_Call) Return(err error) *hubService_UpsertRoute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *hubService_UpsertRoute_Call) RunAndReturn(run func(ctx context.Context, routes []*models.Route) error) *hubService_UpsertRoute_Call {
	_c.Call.Return(run)
	return _c
}

// newPlatformService creates a new instance of platformService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newPlatformService(t interface {
	mock.TestingT
	Cleanup(func())
}) *platformService {
	mock := &platformService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// platformService is an autogenerated mock type for the platformService type
type platformService struct {
	mock.Mock
}

type platformService_Expecter struct {
	mock *mock.Mock
}

func (_m *platformService) EXPECT() *platformService_Expecter {
	return &platformService_Expecter{mock: &_m.Mock}
}

// SendBroadcast provides a mock function for the type platformService
func (_mock *platformService) SendBroadcast(message string) error {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for SendBroadcast")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// platformService_SendBroadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendBroadcast'
type platformService_SendBroadcast_Call struct {
	*mock.Call
}

// SendBroadcast is a helper method to define mock.On call
//   - message string
func (_e *platformService_Expecter) SendBroadcast(message interface{}) *platformService_SendBroadcast_Call {
	return &platformService_SendBroadcast_Call{Call: _e.mock.On("SendBroadcast", message)}
}

func (_c *platformService_SendBroadcast_Call) Run(run func(message string)) *platformService_SendBroadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *platformService_SendBroadcast_Call) Return(err error) *platformService_SendBroadcast_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *platformService_SendBroadcast_Call) RunAndReturn(run func(message string) error) *platformService_SendBroadcast_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessageMulti provides a mock function for the type platformService
func (_mock *platformService) SendMessageMulti(routes []*models.Route, text string) error {
	ret := _mock.Called(routes, text)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageMulti")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*models.Route, string) error); ok {
		r0 = returnFunc(routes, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// platformService_SendMessageMulti_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageMulti'
type platformService_SendMessageMulti_Call struct {
	*mock.Call
}

// SendMessageMulti is a helper method to define mock.On call
//   - routes []*models.Route
//   - text string
func (_e *platformService_Expecter) SendMessageMulti(routes interface{}, text interface{}) *platformService_SendMessageMulti_Call {
	return &platformService_SendMessageMulti_Call{Call: _e.mock.On("SendMessageMulti", routes, text)}
}

func (_c *platformService_SendMessageMulti_Call) Run(run func(routes []*models.Route, text string)) *platformService_SendMessageMulti_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*models.Route
		if args[0] != nil {
			arg0 = args[0].([]*models.Route)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *platformService_SendMessageMulti_Call) Return(err error) *platformService_SendMessageMulti_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *platformService_SendMessageMulti_Call) RunAndReturn(run func(routes []*models.Route, text string) error) *platformService_SendMessageMulti_Call {
	_c.Call.Return(run)
	return _c
}
