// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Iversy/unified-message-hub/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewHubStorage creates a new instance of HubStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHubStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *HubStorage {
	mock := &HubStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HubStorage is an autogenerated mock type for the HubStorage type
type HubStorage struct {
	mock.Mock
}

type HubStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *HubStorage) EXPECT() *HubStorage_Expecter {
	return &HubStorage_Expecter{mock: &_m.Mock}
}

// CreateMessage provides a mock function for the type HubStorage
func (_mock *HubStorage) CreateMessage(ctx context.Context, messageInfos []*models.Message) error {
	ret := _mock.Called(ctx, messageInfos)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.Message) error); ok {
		r0 = returnFunc(ctx, messageInfos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// HubStorage_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type HubStorage_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - messageInfos []*models.Message
func (_e *HubStorage_Expecter) CreateMessage(ctx interface{}, messageInfos interface{}) *HubStorage_CreateMessage_Call {
	return &HubStorage_CreateMessage_Call{Call: _e.mock.On("CreateMessage", ctx, messageInfos)}
}

func (_c *HubStorage_CreateMessage_Call) Run(run func(ctx context.Context, messageInfos []*models.Message)) *HubStorage_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.Message
		if args[1] != nil {
			arg1 = args[1].([]*models.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubStorage_CreateMessage_Call) Return(err error) *HubStorage_CreateMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *HubStorage_CreateMessage_Call) RunAndReturn(run func(ctx context.Context, messageInfos []*models.Message) error) *HubStorage_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertRoute provides a mock function for the type HubStorage
func (_mock *HubStorage) UpsertRoute(ctx context.Context, routes []*models.Route) error {
	ret := _mock.Called(ctx, routes)

	if len(ret) == 0 {
		panic("no return value specified for UpsertRoute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.Route) error); ok {
		r0 = returnFunc(ctx, routes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// HubStorage_UpsertRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertRoute'
type HubStorage_UpsertRoute_Call struct {
	*mock.Call
}

// UpsertRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - routes []*models.Route
func (_e *HubStorage_Expecter) UpsertRoute(ctx interface{}, routes interface{}) *HubStorage_UpsertRoute_Call {
	return &HubStorage_UpsertRoute_Call{Call: _e.mock.On("UpsertRoute", ctx, routes)}
}

func (_c *HubStorage_UpsertRoute_Call) Run(run func(ctx context.Context, routes []*models.Route)) *HubStorage_UpsertRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.Route
		if args[1] != nil {
			arg1 = args[1].([]*models.Route)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HubStorage_UpsertRoute_Call) Return(err error) *HubStorage_UpsertRoute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *HubStorage_UpsertRoute_Call) RunAndReturn(run func(ctx context.Context, routes []*models.Route) error) *HubStorage_UpsertRoute_Call {
	_c.Call.Return(run)
	return _c
}
