// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Iversy/unified-message-hub/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMessageStorage creates a new instance of MessageStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageStorage {
	mock := &MessageStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessageStorage is an autogenerated mock type for the MessageStorage type
type MessageStorage struct {
	mock.Mock
}

type MessageStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageStorage) EXPECT() *MessageStorage_Expecter {
	return &MessageStorage_Expecter{mock: &_m.Mock}
}

// CreateMessage provides a mock function for the type MessageStorage
func (_mock *MessageStorage) CreateMessage(ctx context.Context, messageInfos []*models.Message) error {
	ret := _mock.Called(ctx, messageInfos)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.Message) error); ok {
		r0 = returnFunc(ctx, messageInfos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MessageStorage_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type MessageStorage_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - messageInfos []*models.Message
func (_e *MessageStorage_Expecter) CreateMessage(ctx interface{}, messageInfos interface{}) *MessageStorage_CreateMessage_Call {
	return &MessageStorage_CreateMessage_Call{Call: _e.mock.On("CreateMessage", ctx, messageInfos)}
}

func (_c *MessageStorage_CreateMessage_Call) Run(run func(ctx context.Context, messageInfos []*models.Message)) *MessageStorage_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.Message
		if args[1] != nil {
			arg1 = args[1].([]*models.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MessageStorage_CreateMessage_Call) Return(err error) *MessageStorage_CreateMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MessageStorage_CreateMessage_Call) RunAndReturn(run func(ctx context.Context, messageInfos []*models.Message) error) *MessageStorage_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}
