// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Iversy/unified-message-hub/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMessageStorage creates a new instance of MessageStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageStorage {
	mock := &MessageStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessageStorage is an autogenerated mock type for the MessageStorage type
type MessageStorage struct {
	mock.Mock
}

type MessageStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageStorage) EXPECT() *MessageStorage_Expecter {
	return &MessageStorage_Expecter{mock: &_m.Mock}
}

// CreateMessage provides a mock function for the type MessageStorage
func (_mock *MessageStorage) CreateMessage(ctx context.Context, messageInfos []*models.Message) error {
	ret := _mock.Called(ctx, messageInfos)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.Message) error); ok {
		r0 = returnFunc(ctx, messageInfos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MessageStorage_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type MessageStorage_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - messageInfos []*models.Message
func (_e *MessageStorage_Expecter) CreateMessage(ctx interface{}, messageInfos interface{}) *MessageStorage_CreateMessage_Call {
	return &MessageStorage_CreateMessage_Call{Call: _e.mock.On("CreateMessage", ctx, messageInfos)}
}

func (_c *MessageStorage_CreateMessage_Call) Run(run func(ctx context.Context, messageInfos []*models.Message)) *MessageStorage_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.Message
		if args[1] != nil {
			arg1 = args[1].([]*models.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MessageStorage_CreateMessage_Call) Return(err error) *MessageStorage_CreateMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MessageStorage_CreateMessage_Call) RunAndReturn(run func(ctx context.Context, messageInfos []*models.Message) error) *MessageStorage_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageProducer creates a new instance of MessageProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageProducer {
	mock := &MessageProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessageProducer is an autogenerated mock type for the MessageProducer type
type MessageProducer struct {
	mock.Mock
}

type MessageProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageProducer) EXPECT() *MessageProducer_Expecter {
	return &MessageProducer_Expecter{mock: &_m.Mock}
}

// ProduceMessage provides a mock function for the type MessageProducer
func (_mock *MessageProducer) ProduceMessage(ctx context.Context, key []byte, value []byte, headers map[string]string) error {
	ret := _mock.Called(ctx, key, value, headers)

	if len(ret) == 0 {
		panic("no return value specified for ProduceMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, []byte, map[string]string) error); ok {
		r0 = returnFunc(ctx, key, value, headers)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MessageProducer_ProduceMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceMessage'
type MessageProducer_ProduceMessage_Call struct {
	*mock.Call
}

// ProduceMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - key []byte
//   - value []byte
//   - headers map[string]string
func (_e *MessageProducer_Expecter) ProduceMessage(ctx interface{}, key interface{}, value interface{}, headers interface{}) *MessageProducer_ProduceMessage_Call {
	return &MessageProducer_ProduceMessage_Call{Call: _e.mock.On("ProduceMessage", ctx, key, value, headers)}
}

func (_c *MessageProducer_ProduceMessage_Call) Run(run func(ctx context.Context, key []byte, value []byte, headers map[string]string)) *MessageProducer_ProduceMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 map[string]string
		if args[3] != nil {
			arg3 = args[3].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MessageProducer_ProduceMessage_Call) Return(err error) *MessageProducer_ProduceMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MessageProducer_ProduceMessage_Call) RunAndReturn(run func(ctx context.Context, key []byte, value []byte, headers map[string]string) error) *MessageProducer_ProduceMessage_Call {
	_c.Call.Return(run)
	return _c
}
