// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Iversy/unified-message-hub/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// newMessageProducer creates a new instance of messageProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMessageProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *messageProducer {
	mock := &messageProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// messageProducer is an autogenerated mock type for the messageProducer type
type messageProducer struct {
	mock.Mock
}

type messageProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *messageProducer) EXPECT() *messageProducer_Expecter {
	return &messageProducer_Expecter{mock: &_m.Mock}
}

// ProduceMessage provides a mock function for the type messageProducer
func (_mock *messageProducer) ProduceMessage(ctx context.Context, key []byte, value []byte, headers map[string]string) error {
	ret := _mock.Called(ctx, key, value, headers)

	if len(ret) == 0 {
		panic("no return value specified for ProduceMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, []byte, map[string]string) error); ok {
		r0 = returnFunc(ctx, key, value, headers)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// messageProducer_ProduceMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceMessage'
type messageProducer_ProduceMessage_Call struct {
	*mock.Call
}

// ProduceMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - key []byte
//   - value []byte
//   - headers map[string]string
func (_e *messageProducer_Expecter) ProduceMessage(ctx interface{}, key interface{}, value interface{}, headers interface{}) *messageProducer_ProduceMessage_Call {
	return &messageProducer_ProduceMessage_Call{Call: _e.mock.On("ProduceMessage", ctx, key, value, headers)}
}

func (_c *messageProducer_ProduceMessage_Call) Run(run func(ctx context.Context, key []byte, value []byte, headers map[string]string)) *messageProducer_ProduceMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 map[string]string
		if args[3] != nil {
			arg3 = args[3].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *messageProducer_ProduceMessage_Call) Return(err error) *messageProducer_ProduceMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *messageProducer_ProduceMessage_Call) RunAndReturn(run func(ctx context.Context, key []byte, value []byte, headers map[string]string) error) *messageProducer_ProduceMessage_Call {
	_c.Call.Return(run)
	return _c
}

// newHubService creates a new instance of hubService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newHubService(t interface {
	mock.TestingT
	Cleanup(func())
}) *hubService {
	mock := &hubService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// hubService is an autogenerated mock type for the hubService type
type hubService struct {
	mock.Mock
}

type hubService_Expecter struct {
	mock *mock.Mock
}

func (_m *hubService) EXPECT() *hubService_Expecter {
	return &hubService_Expecter{mock: &_m.Mock}
}

// CreateMessage provides a mock function for the type hubService
func (_mock *hubService) CreateMessage(ctx context.Context, messageInfos []*models.Message) error {
	ret := _mock.Called(ctx, messageInfos)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.Message) error); ok {
		r0 = returnFunc(ctx, messageInfos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// hubService_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type hubService_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - messageInfos []*models.Message
func (_e *hubService_Expecter) CreateMessage(ctx interface{}, messageInfos interface{}) *hubService_CreateMessage_Call {
	return &hubService_CreateMessage_Call{Call: _e.mock.On("CreateMessage", ctx, messageInfos)}
}

func (_c *hubService_CreateMessage_Call) Run(run func(ctx context.Context, messageInfos []*models.Message)) *hubService_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.Message
		if args[1] != nil {
			arg1 = args[1].([]*models.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *hubService_CreateMessage_Call) Return(err error) *hubService_CreateMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *hubService_CreateMessage_Call) RunAndReturn(run func(ctx context.Context, messageInfos []*models.Message) error) *hubService_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}
